#!/bin/bash
#
clear

# Sudo/Admin permission confiramtion

if [[ $EUID -ne 0 ]]

then
	echo
	echo "Exiting, Arp-scan and port scanning need to be run as ROOT, try again with sudo"
	echo
    sleep 3 &&
	exit 1
fi

echo "Enter the network range to begin Arp-Scan" LNET
read $LNET
sleep 2
clear
echo
echo "Recon Started"

# variables
ASCAN=$(arp-scan -l -v | awk '{print $1}' | grep $LNET* | sort | uniq  > ipaddres)
ipaddres=$IPADD

nmap -sS -sC -sV -O -p- -D 1.1.1.1,8.8.8.8 -iL $IPADD -oX NetReport
NetReport=$RSLTS

mkdir -p $PWD/NetworkReport
mv NetReport $PWD/NetworkReport/
clear
echo "The Results Report will be on NetworkReport directory"
echo
echo
cat $PWD/NetworkReport/$RSLTS


#sudo arp-scan -l -v | awk '{print $1}' | grep 192.* |  sort | uniq  > addressestoscan.json && sudo nmap -sS -sC -sV -O -p- -D 1.1.1.1,8.8.8.8 -iL addressestoscan.json -oX LocalNetReport

