#!/usr/bin/env bash
#
clear

# Sudo/Admin permission confiramtion

if [[ $EUID -ne 0 ]]

then
	echo
	echo "Exiting, Arp-scan and port scanning need to be run as ROOT, try again with sudo"
	echo
    sleep 3 &&
	exit 1
fi

arp | awk {'print $1'} | sort | uniq >> temp_ips.xml | cat temp_ips.xml | sort | uniq >> uniq_ips.xml &&
    nmap -sC -sV -O -p- -D 1.1.1.1,8.8.8.8 -iL uniq_ips.xml -oX ./NetworkReport &&
    sleep 2

xdg-open NetworkReport*

clear
echo "Here's your Report and details about every Device"

#sudo arp-scan -l -v | awk '{print $1}' | grep 192.* |  sort | uniq  > addressestoscan.json && sudo nmap -sS -sC -sV -O -p- -D 1.1.1.1,8.8.8.8 -iL addressestoscan.json -oX LocalNetReport
