#!/bin/bash
# Correct way to chnage MAC on NIC and refresh IPaddress Also
clear

sudo ip link set eth0 down && sudo macchanger -p eth0 &&

sudo ip link set eth0 up &&

sleep 3

ip a | awk '{print $2}' | grep 192.* | cut -b 1-12 &&

echo "All Back to Normal!!"